package com.payby.export.demo.ui.entity

data class Response(
    var applyStatus: Int = -1,
    var responseTime: Long = 0,
    var messageId: String ? = null,
    var messageType: String ? = null,
    var functionName: String ? = null,
    var responseCode: String ? = null,
    var responseMessage: String ? = null,

    var orderNo: String ? = null,           // PayBy System Order Number
    var misOrderNo: String ? = null,
    var merchantOrderNo: String ? = null,   // Merchant order number, generated by the pos machine, which is unique within a merchant system

    var subject: String ? = null,
    var payMethod: String ? = null,
    var tipAmount: Double = 0.00,
    var totalAmount: Double = 0.00,

    var deviceId: String ? = null,
    var appVersion: String ? = null,
    var terminalNo: String ? = null,
    var merchantNo: String ? = null,
    var packageName: String ? = null,
    var merchantName: String ? = null,

    var cardType: String ? = null,
    var cardNoMask: String ? = null,
    var cardHolderName: String ? = null,
    var cardOrganization: String ? = null,

    var voucherNo: String ? = null,
    var referenceNo: String ? = null,
    var authorizationNo: String ? = null,
    var transactionType: String ? = null,
    var transactionDate: String ? = null,
    var transactionTime: String ? = null,
    var emvTag: EmvTag ? = null,
)